name: seahorse-app
region: london  
workers:  
  - name: worker  
    environment_slug: python  
    github:  
      repo: Doubleshi/Discord_Bot 
      branch: main  
    instance_count: 1  
    instance_size_slug: basic-xxs 
    run_command: python Sbot.py 